import { extractRequirementIds, formatTaskId } from "../utils/id-contracts.js";
import { currentTimestamp } from "../utils/runtime-context.js";
import type { FileManager } from "./file-manager.js";

export const SPECKY_SCAFFOLD_MARKER = "specky_scaffold: true";

export interface FeaturePackageInput {
  featureDir: string;
  featureNumber: string;
  featureName: string;
  specContent: string;
  sourceTool: string;
}

export interface FeaturePackageResult {
  created: string[];
  existing: string[];
}

interface ArtifactDefinition {
  fileName: string;
  content: string;
}

export class FeaturePackageGenerator {
  constructor(private readonly fileManager: FileManager) {}

  async ensureFeaturePackage(input: FeaturePackageInput): Promise<FeaturePackageResult> {
    const artifacts = this.buildArtifacts(input);
    const created: string[] = [];
    const existing: string[] = [];

    for (const artifact of artifacts) {
      const relativePath = `${input.featureDir}/${artifact.fileName}`;
      if (await this.fileManager.fileExists(relativePath)) {
        existing.push(artifact.fileName);
        continue;
      }
      await this.fileManager.writeSpecFile(
        input.featureDir,
        artifact.fileName,
        artifact.content,
        false,
      );
      created.push(artifact.fileName);
    }

    return { created, existing };
  }

  private buildArtifacts(input: FeaturePackageInput): ArtifactDefinition[] {
    const requirementIds = extractRequirementIds(input.specContent);
    const generatedAt = currentTimestamp();
    const safeTitle = this.titleize(input.featureName);

    return [
      {
        fileName: "README.md",
        content: this.buildReadme(input, requirementIds, generatedAt, safeTitle),
      },
      {
        fileName: "DESIGN.md",
        content: this.buildDesignScaffold(input, requirementIds, generatedAt, safeTitle),
      },
      {
        fileName: "TASKS.md",
        content: this.buildTasksScaffold(input, requirementIds, generatedAt, safeTitle),
      },
      { fileName: "ADR.md", content: this.buildAdr(input, requirementIds, generatedAt, safeTitle) },
      {
        fileName: "PLAYBOOK.md",
        content: this.buildPlaybook(input, requirementIds, generatedAt, safeTitle),
      },
      {
        fileName: "DIAGRAMS.md",
        content: this.buildDiagrams(input, requirementIds, generatedAt, safeTitle),
      },
      {
        fileName: "TDD_STATUS.md",
        content: this.buildTddStatus(input, requirementIds, generatedAt, safeTitle),
      },
      {
        fileName: "EVIDENCE.md",
        content: this.buildEvidence(input, requirementIds, generatedAt, safeTitle),
      },
      {
        fileName: "SPEC_PACKAGE.json",
        content: this.buildManifest(input, requirementIds, generatedAt),
      },
    ];
  }

  private titleize(value: string): string {
    return value
      .replace(/[-_]+/g, " ")
      .replace(/\s+/g, " ")
      .trim()
      .replace(/\b\w/g, (char) => char.toUpperCase());
  }

  private frontmatter(
    title: string,
    featureId: string,
    generatedAt: string,
    scaffold = false,
  ): string {
    return [
      "---",
      `title: "${title}"`,
      `feature_id: "${featureId}"`,
      `generated_at: "${generatedAt}"`,
      `status: "Draft"`,
      ...(scaffold ? [SPECKY_SCAFFOLD_MARKER] : []),
      "---",
      "",
    ].join("\n");
  }

  private requirementList(requirementIds: string[]): string {
    if (requirementIds.length === 0) return "- No REQ-IDs found yet. Review SPECIFICATION.md.";
    return requirementIds.map((reqId) => `- ${reqId}`).join("\n");
  }

  private buildReadme(
    input: FeaturePackageInput,
    requirementIds: string[],
    generatedAt: string,
    safeTitle: string,
  ): string {
    return [
      this.frontmatter(
        `${safeTitle} Feature Package`,
        `${input.featureNumber}-${input.featureName}`,
        generatedAt,
      ),
      `# ${safeTitle} Feature Package`,
      "",
      "This package was generated by Specky to keep specification, design, tasks, tests, diagrams, decisions, and evidence together from the moment the feature is created.",
      "",
      "## Required Artifacts",
      "",
      "| Artifact | Purpose | Status |",
      "| --- | --- | --- |",
      "| CONSTITUTION.md | Scope, principles, and constraints | Required |",
      "| SPECIFICATION.md | EARS requirements and acceptance criteria | Required |",
      "| DESIGN.md | Architecture and design decisions | Scaffold until completed |",
      "| TASKS.md | Implementation task breakdown | Scaffold until completed |",
      "| ADR.md | Architecture decision records | Draft |",
      "| PLAYBOOK.md | Operating playbook for this feature | Draft |",
      "| DIAGRAMS.md | Mermaid diagrams for architecture and flow | Draft |",
      "| TDD_STATUS.md | Red, green, refactor and requirement coverage status | Draft |",
      "| EVIDENCE.md | Commands, validation, audit, and release evidence | Draft |",
      "| SPEC_PACKAGE.json | Machine-readable completion manifest | Draft |",
      "",
      "## Requirements",
      "",
      this.requirementList(requirementIds),
      "",
      "## Next Steps",
      "",
      "1. Review SPECIFICATION.md for EARS correctness and completeness.",
      "2. Replace DESIGN.md scaffold with the approved architecture.",
      "3. Replace TASKS.md scaffold with traceable implementation tasks.",
      "4. Generate or update diagrams, tests, verification, and evidence before release.",
      "",
    ].join("\n");
  }

  private buildDesignScaffold(
    input: FeaturePackageInput,
    requirementIds: string[],
    generatedAt: string,
    safeTitle: string,
  ): string {
    return [
      this.frontmatter(
        `${safeTitle} Design Scaffold`,
        `${input.featureNumber}-${input.featureName}`,
        generatedAt,
        true,
      ),
      `# ${safeTitle} Design`,
      "",
      "> This is a Specky scaffold. Replace it with `sdd_write_design` before advancing beyond the Design phase.",
      "",
      "## System Context",
      "",
      "Describe users, systems, trust boundaries, and external dependencies.",
      "",
      "## Container Architecture",
      "",
      "Describe deployable units, data stores, interfaces, and runtime responsibilities.",
      "",
      "## Component Design",
      "",
      "Describe modules, services, contracts, and implementation boundaries.",
      "",
      "## Data Model",
      "",
      "Document entities, persistence, retention, and classification.",
      "",
      "## API Contracts",
      "",
      "Document endpoints, requests, responses, errors, and versioning.",
      "",
      "## Requirement Traceability",
      "",
      this.requirementList(requirementIds),
      "",
      "## References",
      "",
      "- Add official product, platform, or standards references used by this design.",
      "",
    ].join("\n");
  }

  private buildTasksScaffold(
    input: FeaturePackageInput,
    requirementIds: string[],
    generatedAt: string,
    safeTitle: string,
  ): string {
    const taskRows =
      requirementIds.length === 0
        ? `- [ ] ${formatTaskId(1)}: Review SPECIFICATION.md and add traceable implementation tasks. [P] traces_to: TBD`
        : requirementIds
            .map(
              (reqId, index) =>
                `- [ ] ${formatTaskId(index + 1)}: Implement and verify ${reqId}. traces_to: ${reqId}`,
            )
            .join("\n");

    return [
      this.frontmatter(
        `${safeTitle} Tasks Scaffold`,
        `${input.featureNumber}-${input.featureName}`,
        generatedAt,
        true,
      ),
      `# ${safeTitle} Tasks`,
      "",
      "> This is a Specky scaffold. Replace it with `sdd_write_tasks` before advancing beyond the Tasks phase.",
      "",
      "## Pre-Implementation Gates",
      "",
      "- [ ] SPECIFICATION.md reviewed and accepted.",
      "- [ ] DESIGN.md completed and mapped to all REQ-IDs.",
      "- [ ] TDD_STATUS.md initialized.",
      "- [ ] DIAGRAMS.md updated.",
      "",
      "## Tasks",
      "",
      taskRows,
      "",
    ].join("\n");
  }

  private buildAdr(
    input: FeaturePackageInput,
    requirementIds: string[],
    generatedAt: string,
    safeTitle: string,
  ): string {
    return [
      this.frontmatter(
        `${safeTitle} Architecture Decisions`,
        `${input.featureNumber}-${input.featureName}`,
        generatedAt,
      ),
      `# ${safeTitle} Architecture Decision Records`,
      "",
      "## ADR-001: Establish Initial Feature Package",
      "",
      "**Status:** Proposed",
      "",
      "**Context:** Specky creates a complete feature package so requirements, design, tasks, diagrams, TDD status, and evidence are tracked together from the start.",
      "",
      "**Decision:** Keep all feature-specific decision records in this file unless the feature needs separate ADR files.",
      "",
      "**Consequences:** Every material design decision must trace to one or more REQ-IDs and must be updated before release.",
      "",
      "**Traces To:**",
      "",
      this.requirementList(requirementIds),
      "",
      "## References",
      "",
      "- Add standards, vendor docs, or architecture references used by decisions.",
      "",
    ].join("\n");
  }

  private buildPlaybook(
    input: FeaturePackageInput,
    requirementIds: string[],
    generatedAt: string,
    safeTitle: string,
  ): string {
    return [
      this.frontmatter(
        `${safeTitle} Playbook`,
        `${input.featureNumber}-${input.featureName}`,
        generatedAt,
      ),
      `# ${safeTitle} Playbook`,
      "",
      "## Purpose",
      "",
      "This playbook describes how to validate, implement, test, operate, and release this feature.",
      "",
      "## Implementation Flow",
      "",
      "1. Confirm EARS requirements in SPECIFICATION.md.",
      "2. Complete DESIGN.md and ADR.md.",
      "3. Complete TASKS.md with REQ-ID traceability.",
      "4. Generate tests and property-based tests.",
      "5. Update TDD_STATUS.md after red, green, and refactor phases.",
      "6. Run verification and update EVIDENCE.md.",
      "7. Run release gates before PR or publish.",
      "",
      "## Required Requirement Coverage",
      "",
      this.requirementList(requirementIds),
      "",
      "## Validation Commands",
      "",
      "```bash",
      "npm run build",
      "npm test",
      "npm run test:coverage",
      "npm audit --audit-level=high",
      "```",
      "",
    ].join("\n");
  }

  private buildDiagrams(
    input: FeaturePackageInput,
    requirementIds: string[],
    generatedAt: string,
    safeTitle: string,
  ): string {
    const firstReq = requirementIds[0] ?? "REQ-TBD-001";
    return [
      this.frontmatter(
        `${safeTitle} Diagrams`,
        `${input.featureNumber}-${input.featureName}`,
        generatedAt,
      ),
      `# ${safeTitle} Diagrams`,
      "",
      "## C4 Context",
      "",
      "```mermaid",
      "C4Context",
      `  title ${safeTitle} - System Context`,
      '  Person(user, "User", "Primary user of the feature")',
      `  System(feature, "${safeTitle}", "Feature under specification")`,
      '  Rel(user, feature, "Uses")',
      "```",
      "",
      "## Component Flow",
      "",
      "```mermaid",
      "flowchart LR",
      `  ${firstReq}[${firstReq}] --> Design[Design]`,
      "  Design --> Tasks[Tasks]",
      "  Tasks --> Tests[Tests]",
      "  Tests --> Evidence[Evidence]",
      "```",
      "",
      "## Required Diagram Updates",
      "",
      "- Add C4 Container diagram.",
      "- Add C4 Component diagram.",
      "- Add Sequence diagram for the critical path.",
      "- Add Data Flow diagram.",
      "- Add Deployment diagram when infrastructure exists.",
      "",
    ].join("\n");
  }

  private buildTddStatus(
    input: FeaturePackageInput,
    requirementIds: string[],
    generatedAt: string,
    safeTitle: string,
  ): string {
    const rows =
      requirementIds.length === 0
        ? "| TBD | Pending | Pending | Pending | No REQ-ID detected yet |"
        : requirementIds
            .map((reqId) => `| ${reqId} | Pending | Pending | Pending | Add test evidence |`)
            .join("\n");

    return [
      this.frontmatter(
        `${safeTitle} TDD Status`,
        `${input.featureNumber}-${input.featureName}`,
        generatedAt,
      ),
      `# ${safeTitle} TDD Status`,
      "",
      "## TDD Matrix",
      "",
      "| Requirement | Red | Green | Refactor | Evidence |",
      "| --- | --- | --- | --- | --- |",
      rows,
      "",
      "## Commands",
      "",
      "```bash",
      "npm test",
      "npm run test:coverage",
      "```",
      "",
      "## Notes",
      "",
      "Update this file whenever tests are added, fixed, refactored, or mapped to REQ-IDs.",
      "",
    ].join("\n");
  }

  private buildEvidence(
    input: FeaturePackageInput,
    requirementIds: string[],
    generatedAt: string,
    safeTitle: string,
  ): string {
    return [
      this.frontmatter(
        `${safeTitle} Evidence`,
        `${input.featureNumber}-${input.featureName}`,
        generatedAt,
      ),
      `# ${safeTitle} Evidence`,
      "",
      "## Generation Evidence",
      "",
      `- Source tool: ${input.sourceTool}`,
      `- Generated at: ${generatedAt}`,
      `- Requirements detected: ${requirementIds.length}`,
      "",
      "## Required Evidence Before Release",
      "",
      "- [ ] Build output recorded.",
      "- [ ] Unit and integration test output recorded.",
      "- [ ] Coverage output recorded.",
      "- [ ] Security audit output recorded.",
      "- [ ] Diagram review completed.",
      "- [ ] Audit chain verified.",
      "- [ ] Release checklist completed.",
      "",
      "## References",
      "",
      "- Add links to official docs, standards, or issue/PR evidence used for this feature.",
      "",
    ].join("\n");
  }

  private buildManifest(
    input: FeaturePackageInput,
    requirementIds: string[],
    generatedAt: string,
  ): string {
    return (
      JSON.stringify(
        {
          schema_version: "1.0.0",
          feature_number: input.featureNumber,
          feature_name: input.featureName,
          feature_dir: input.featureDir,
          source_tool: input.sourceTool,
          generated_at: generatedAt,
          requirements: requirementIds,
          required_artifacts: [
            "CONSTITUTION.md",
            "SPECIFICATION.md",
            "DESIGN.md",
            "TASKS.md",
            "ADR.md",
            "PLAYBOOK.md",
            "DIAGRAMS.md",
            "TDD_STATUS.md",
            "EVIDENCE.md",
            "SPEC_PACKAGE.json",
          ],
          completion: {
            design_final: false,
            tasks_final: false,
            diagrams_reviewed: false,
            tdd_status_updated: false,
            evidence_updated: false,
            audit_verified: false,
          },
        },
        null,
        2,
      ) + "\n"
    );
  }
}
