/**
 * gitignore-writer.test.ts — Specky-managed .gitignore block writer.
 */
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { writeGitignoreBlock } from "../../src/cli/lib/gitignore-writer.js";

const BLOCK_START = "# ─── Specky (vendored — regenerated by `specky install`) ───";
const BLOCK_END = "# ─── end Specky ───";

const workspaces: string[] = [];

function setup(): string {
  const workspace = mkdtempSync(join(tmpdir(), "specky-gitignore-writer-"));
  workspaces.push(workspace);
  return workspace;
}

function gitignorePath(workspace: string): string {
  return resolve(workspace, ".gitignore");
}

function readGitignore(workspace: string): string {
  return readFileSync(gitignorePath(workspace), "utf8");
}

afterEach(() => {
  while (workspaces.length > 0) {
    rmSync(workspaces.pop() as string, { recursive: true, force: true });
  }
});

describe("writeGitignoreBlock — creating a new .gitignore", () => {
  it("creates .gitignore with the Specky block when none exists", () => {
    const workspace = setup();

    const result = writeGitignoreBlock(workspace, { dryRun: false });

    expect(result.action).toBe("created");
    expect(result.path).toBe(gitignorePath(workspace));
    expect(result.linesAdded).toBeGreaterThan(0);

    const content = readGitignore(workspace);
    expect(content).toContain(BLOCK_START);
    expect(content).toContain(BLOCK_END);
    expect(content).toContain(".claude/agents/");
    expect(content).toContain(".specky/install.json");
    expect(content.endsWith("\n")).toBe(true);
    // The created file is exactly the block plus a trailing newline.
    expect(result.linesAdded).toBe(content.trimEnd().split("\n").length);
  });

  it("dry-run reports 'created' without writing any file", () => {
    const workspace = setup();

    const result = writeGitignoreBlock(workspace, { dryRun: true });

    expect(result.action).toBe("created");
    expect(result.linesAdded).toBeGreaterThan(0);
    expect(existsSync(gitignorePath(workspace))).toBe(false);
  });

  it("throws when the workspace directory does not exist", () => {
    const missing = join(tmpdir(), "specky-gitignore-nonexistent-dir");

    expect(() => writeGitignoreBlock(missing, { dryRun: false })).toThrow();
    // Dry-run must not throw even though the directory is missing.
    expect(() => writeGitignoreBlock(missing, { dryRun: true })).not.toThrow();
  });
});

describe("writeGitignoreBlock — appending to existing content", () => {
  it("appends the block after user-authored entries and preserves them", () => {
    const workspace = setup();
    writeFileSync(gitignorePath(workspace), "node_modules/\ndist/\n", "utf8");

    const result = writeGitignoreBlock(workspace, { dryRun: false });

    expect(result.action).toBe("updated");
    expect(result.linesAdded).toBeGreaterThan(0);

    const content = readGitignore(workspace);
    expect(content.startsWith("node_modules/\ndist/\n")).toBe(true);
    expect(content).toContain(BLOCK_START);
    expect(content.indexOf("node_modules/")).toBeLessThan(content.indexOf(BLOCK_START));
  });

  it("inserts a newline separator when existing content lacks a trailing newline", () => {
    const workspace = setup();
    writeFileSync(gitignorePath(workspace), "node_modules/", "utf8");

    writeGitignoreBlock(workspace, { dryRun: false });

    const content = readGitignore(workspace);
    // No line is merged: the block header starts on its own line.
    expect(content).toMatch(/node_modules\/\n\n#/);
    expect(content).toContain(BLOCK_START);
  });

  it("dry-run reports 'updated' without modifying existing content", () => {
    const workspace = setup();
    const original = "node_modules/\n";
    writeFileSync(gitignorePath(workspace), original, "utf8");

    const result = writeGitignoreBlock(workspace, { dryRun: true });

    expect(result.action).toBe("updated");
    expect(result.linesAdded).toBeGreaterThan(0);
    expect(readGitignore(workspace)).toBe(original);
  });
});

describe("writeGitignoreBlock — updating an existing block", () => {
  it("is idempotent: a second run reports 'already-present' and changes nothing", () => {
    const workspace = setup();
    writeGitignoreBlock(workspace, { dryRun: false });
    const afterFirst = readGitignore(workspace);

    const result = writeGitignoreBlock(workspace, { dryRun: false });

    expect(result.action).toBe("already-present");
    expect(result.linesAdded).toBe(0);
    expect(readGitignore(workspace)).toBe(afterFirst);
  });

  it("replaces an outdated block in place while preserving surrounding content", () => {
    const workspace = setup();
    const before = "node_modules/\n";
    const after = "\n# custom footer\n";
    const outdated = `${BLOCK_START}\n.old/specky-path/\n${BLOCK_END}`;
    writeFileSync(gitignorePath(workspace), before + outdated + after, "utf8");

    const result = writeGitignoreBlock(workspace, { dryRun: false });

    expect(result.action).toBe("updated");
    expect(result.linesAdded).toBe(0);

    const content = readGitignore(workspace);
    // Stale entry replaced by the current block.
    expect(content).not.toContain(".old/specky-path/");
    expect(content).toContain(".specky/install.json");
    // User content around the block is untouched.
    expect(content.startsWith(before)).toBe(true);
    expect(content.endsWith(after)).toBe(true);
    // Exactly one block remains.
    expect(content.split(BLOCK_START)).toHaveLength(2);
    expect(content.split(BLOCK_END)).toHaveLength(2);
  });

  it("dry-run reports 'updated' for an outdated block without writing", () => {
    const workspace = setup();
    const original = `${BLOCK_START}\n.old/specky-path/\n${BLOCK_END}\n`;
    writeFileSync(gitignorePath(workspace), original, "utf8");

    const result = writeGitignoreBlock(workspace, { dryRun: true });

    expect(result.action).toBe("updated");
    expect(readGitignore(workspace)).toBe(original);
  });

  it("appends a fresh block when only the start marker is present (no end marker)", () => {
    const workspace = setup();
    const original = `${BLOCK_START}\n.dangling/\n`;
    writeFileSync(gitignorePath(workspace), original, "utf8");

    const result = writeGitignoreBlock(workspace, { dryRun: false });

    expect(result.action).toBe("updated");
    const content = readGitignore(workspace);
    expect(content.startsWith(original)).toBe(true);
    expect(content).toContain(BLOCK_END);
  });
});
