import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { FileManager } from "../../src/services/file-manager.js";
import { TranscriptParser } from "../../src/services/transcript-parser.js";
import type { TranscriptAnalysis } from "../../src/types.js";

const workspaces: string[] = [];

afterEach(() => {
  for (const workspace of workspaces.splice(0)) {
    rmSync(workspace, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
  }
});

function makeParser(): { parser: TranscriptParser; workspace: string } {
  const workspace = mkdtempSync(join(tmpdir(), "specky-transcript-parser-"));
  workspaces.push(workspace);
  return { parser: new TranscriptParser(new FileManager(workspace)), workspace };
}

const VTT_BASIC = `WEBVTT

NOTE
Auto-generated by the meeting recorder
and should be ignored

00:00:01.000 --> 00:00:04.000
<v Alice>Welcome to the quarterly review.</v>

00:00:05.000 --> 00:00:09.000
Bob: Thanks for joining today.

00:00:10.000 --> 00:00:15.000
<v Carol>We must review the <b>budget</b> numbers.</v>

00:00:20.000 --> 00:00:25.000
<v Dave:>Closing the call now.</v>
`;

describe("TranscriptParser — VTT format", () => {
  it("parses cues with <v Speaker> tags and Speaker: prefixes", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(VTT_BASIC, "vtt");

    expect(analysis.segments).toHaveLength(4);
    expect(analysis.segments[0]).toEqual({
      speaker: "Alice",
      text: "Welcome to the quarterly review.",
      timestamp: "00:00:01.000 --> 00:00:04.000",
    });
    expect(analysis.segments[1]).toMatchObject({
      speaker: "Bob",
      text: "Thanks for joining today.",
    });
    expect(analysis.segments[3]).toMatchObject({ speaker: "Dave:", text: "Closing the call now." });
  });

  it("removes the WEBVTT header and NOTE blocks from the content", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(VTT_BASIC, "vtt");

    expect(analysis.full_text).not.toContain("Auto-generated");
    expect(analysis.full_text).not.toContain("WEBVTT");
  });

  it("strips HTML tags from cue text", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(VTT_BASIC, "vtt");

    expect(analysis.segments[2].text).toBe("We must review the budget numbers.");
  });

  it("strips the trailing colon from <v Speaker:> participants", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(VTT_BASIC, "vtt");

    expect(analysis.participants).toEqual(["Alice", "Bob", "Carol", "Dave"]);
  });

  it("joins multi-line cue text and skips blocks without usable text", () => {
    const { parser } = makeParser();
    const vtt = `WEBVTT - recorder export

intro text before any cue

cue-17
00:01:00.000 --> 00:01:05.000
First line of the cue
second line of the cue

00:02:00.000 --> 00:02:05.000

00:03:00.000 --> 00:03:05.000
Plain text without a speaker tag
`;
    const analysis = parser.parse(vtt, "vtt");

    expect(analysis.segments).toHaveLength(2);
    expect(analysis.segments[0]).toMatchObject({
      speaker: "",
      text: "First line of the cue second line of the cue",
    });
    expect(analysis.segments[1]).toMatchObject({
      speaker: "",
      text: "Plain text without a speaker tag",
      timestamp: "00:03:00.000 --> 00:03:05.000",
    });
  });

  it("computes the duration from the first and last cue timestamps", () => {
    const { parser } = makeParser();
    const vtt = `WEBVTT

00:00:00.000 --> 00:00:04.000
Alice: Start of the meeting notes.

00:10:00.000 --> 00:10:05.000
Bob: Closing remarks for the meeting.
`;
    const analysis = parser.parse(vtt, "vtt");

    expect(analysis.duration_estimate).toBe("~10 minutes");
  });

  it("falls back to text-volume estimation when cue timestamps do not advance", () => {
    const { parser } = makeParser();
    const vtt = `WEBVTT

00:00:00.000 --> 00:00:00.500
Alice: one two three four five

00:00:00.500 --> 00:00:00.500
Bob: six seven eight nine ten
`;
    const analysis = parser.parse(vtt, "vtt");

    expect(analysis.duration_estimate).toBe("~1 minutes (estimated from text volume)");
  });
});

describe("TranscriptParser — SRT format", () => {
  const SRT = `1
00:00:01,000 --> 00:00:04,000
Alice: Welcome to the quarterly review.

2
00:00:05,000 --> 00:00:09,000
Bob: Thanks for <i>joining</i> the call today.

3
00:00:10,000 --> 00:00:15,000
No speaker attribution on this line
and a second line of the same cue.

4
00:00:40,000 --> 00:00:45,000
Carol: <b><i>Nested</i></b> formatting here.

5
00:00:20,000 --> 00:00:25,000
<b></b>

6

00:00:30,000 --> 00:00:35,000
Dangling timestamp block without an index line.
`;

  it("parses index/timestamp/text blocks with speaker prefixes", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(SRT, "srt");

    expect(analysis.segments[0]).toEqual({
      speaker: "Alice",
      text: "Welcome to the quarterly review.",
      timestamp: "00:00:01,000 --> 00:00:04,000",
    });
    expect(analysis.participants).toEqual(["Alice", "Bob", "Carol"]);
  });

  it("strips nested HTML tags and joins multi-line cue text", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(SRT, "srt");

    expect(analysis.segments[1].text).toBe("Thanks for joining the call today.");
    expect(analysis.segments[2]).toMatchObject({
      speaker: "",
      text: "No speaker attribution on this line and a second line of the same cue.",
    });
    expect(analysis.segments[3].text).toBe("Nested formatting here.");
  });

  it("skips blocks with fewer than three lines or with empty stripped text", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(SRT, "srt");

    expect(analysis.segments).toHaveLength(4);
    expect(analysis.full_text).not.toContain("Dangling");
  });

  it("falls back to text-volume estimation when timestamps are not parseable", () => {
    const { parser } = makeParser();
    const srt = `1
not-a-timestamp
Alice: some words here for the estimate

2
also-not-a-timestamp
Bob: more words here for the estimate
`;
    const analysis = parser.parse(srt, "srt");

    expect(analysis.duration_estimate).toContain("(estimated from text volume)");
  });
});

describe("TranscriptParser — plain text format", () => {
  it("splits capitalized Speaker: prefixes from unattributed lines", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(
      [
        "Alice: Welcome to the sync.",
        "bob: lowercase names are not detected as speakers.",
        "",
        "Just a floating line with no attribution.",
      ].join("\n"),
      "txt",
    );

    expect(analysis.segments).toHaveLength(3);
    expect(analysis.segments[0]).toEqual({ speaker: "Alice", text: "Welcome to the sync." });
    expect(analysis.segments[1]).toEqual({
      speaker: "",
      text: "bob: lowercase names are not detected as speakers.",
    });
    expect(analysis.segments[2]).toEqual({
      speaker: "",
      text: "Just a floating line with no attribution.",
    });
    expect(analysis.participants).toEqual(["Alice"]);
  });

  it("defaults to the txt format when none is given", () => {
    const { parser } = makeParser();
    const analysis = parser.parse("Alice: hello there everyone");

    expect(analysis.segments).toEqual([{ speaker: "Alice", text: "hello there everyone" }]);
  });

  it("returns an empty analysis skeleton for empty content", () => {
    const { parser } = makeParser();
    const analysis = parser.parse("", "txt");

    expect(analysis.title).toBe("Meeting Transcript");
    expect(analysis.segments).toEqual([]);
    expect(analysis.participants).toEqual([]);
    expect(analysis.topics).toEqual([]);
    expect(analysis.decisions).toEqual([]);
    expect(analysis.action_items).toEqual([]);
    expect(analysis.full_text).toBe("");
    expect(analysis.duration_estimate).toBe("~1 minutes (estimated from text volume)");
  });
});

describe("TranscriptParser — plain markdown format", () => {
  it("parses bold speakers, plain speakers, bullets, and stray lines", () => {
    const { parser } = makeParser();
    const md = [
      "# Launch Notes",
      "",
      "**Alice:** Let's review the launch plan.",
      "**Bob** confirmed the date works",
      "Carol: The invites go out tomorrow.",
      "- Action bullet without owner",
      "A stray note with no attribution at all.",
      "---",
      "",
      "# Another Heading",
    ].join("\n");
    const analysis = parser.parse(md, "md");

    expect(analysis.segments).toHaveLength(5);
    expect(analysis.segments[0]).toEqual({
      speaker: "Alice",
      text: "Let's review the launch plan.",
    });
    expect(analysis.segments[1]).toEqual({ speaker: "Bob", text: "confirmed the date works" });
    expect(analysis.segments[2]).toEqual({
      speaker: "Carol",
      text: "The invites go out tomorrow.",
    });
    expect(analysis.segments[3]).toEqual({ speaker: "", text: "Action bullet without owner" });
    expect(analysis.segments[4]).toEqual({
      speaker: "",
      text: "A stray note with no attribution at all.",
    });
    expect(analysis.participants).toEqual(["Alice", "Bob", "Carol"]);
  });
});

describe("TranscriptParser — Power Automate markdown format", () => {
  const POWER_AUTOMATE = `---
title: "Quarterly Planning"
date: "2026-07-10"
language: "en"
author: "Copilot Agent"
version: "1.0"
description: "Q3 planning session"
tags: ["planning", "q3"]
---

# Quarterly Planning

> Align on Q3 goals for the platform team.

## 1. Executive Summary

- The team reviewed the roadmap and the hiring plan.
Budget constraints for Q3 were also discussed at length.

## 2. Meeting Details

| Key | Value |
| --- | --- |
| **Date** | 2026-07-10 |
| **Participants** | Alice Silva, Bob Costa, Carol Dias |
| **Organizer** | Alice Silva |

## 3. Main Topics

1. Roadmap review
2. Hiring plan
3. Budget allocation

## 4. Complete Transcription

### Morning session

**Alice Silva:** Welcome everyone, let's start with the roadmap.
[00:01:23] **Bob Costa**: The roadmap looks solid but we must validate dependencies.
**Carol Dias:** What is the hiring timeline for Q3?
We should revisit the hiring plan after the budget review.

## 5. Action Items

- [ ] Bob Costa: Validate the dependency list by Friday
- [x] Carol Dias: Draft the hiring plan
- Alice Silva: Schedule the follow-up meeting

## 6. References

- Q3 roadmap deck
- Hiring tracker document

## Change Log

| Version | Date | Author | Changes |
| 1.0 | 2026-07-10 | Agent | Initial |
`;

  it("extracts the title and all YAML frontmatter metadata", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(POWER_AUTOMATE, "md");

    expect(analysis.title).toBe("Quarterly Planning");
    const meta = new Map(
      analysis.segments
        .filter((segment) => segment.speaker.startsWith("__META_"))
        .map((segment) => [segment.speaker, segment.text]),
    );
    expect(meta.get("__META_TITLE__")).toBe("Quarterly Planning");
    expect(meta.get("__META_DATE__")).toBe("2026-07-10");
    expect(meta.get("__META_LANGUAGE__")).toBe("en");
    expect(meta.get("__META_AUTHOR__")).toBe("Copilot Agent");
    expect(meta.get("__META_VERSION__")).toBe("1.0");
    expect(meta.get("__META_DESCRIPTION__")).toBe("Q3 planning session");
    expect(meta.get("__META_TAGS__")).toBe("planning, q3");
  });

  it("merges the organizer into the participants table entry", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(POWER_AUTOMATE, "md");

    expect(analysis.participants).toEqual(["Alice Silva", "Bob Costa", "Carol Dias"]);
    const participantSegments = analysis.segments.filter(
      (segment) => segment.speaker === "__META_PARTICIPANTS__",
    );
    expect(participantSegments).toHaveLength(1);
    expect(participantSegments[0].text).toBe("Alice Silva, Alice Silva, Bob Costa, Carol Dias");
  });

  it("collects summary bullets and paragraphs from the executive summary", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(POWER_AUTOMATE, "md");

    const summaries = analysis.segments
      .filter((segment) => segment.speaker === "__SUMMARY__")
      .map((segment) => segment.text);
    expect(summaries).toEqual([
      "Align on Q3 goals for the platform team.",
      "The team reviewed the roadmap and the hiring plan.",
      "Budget constraints for Q3 were also discussed at length.",
    ]);
  });

  it("uses the Main Topics section as explicit topics", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(POWER_AUTOMATE, "md");

    expect(analysis.topics.map((topic) => topic.name)).toEqual([
      "Roadmap review",
      "Hiring plan",
      "Budget allocation",
    ]);
    expect(analysis.topics[0]).toMatchObject({
      summary: "Roadmap review",
      speakers: [],
      key_points: ["Roadmap review"],
    });
  });

  it("parses bold, timestamped, and continuation lines in the transcription section", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(POWER_AUTOMATE, "md");

    expect(analysis.segments).toContainEqual({
      speaker: "Alice Silva",
      text: "Welcome everyone, let's start with the roadmap.",
    });
    expect(analysis.segments).toContainEqual({
      speaker: "Bob Costa",
      text: "The roadmap looks solid but we must validate dependencies.",
      timestamp: "00:01:23",
    });
    expect(analysis.segments).toContainEqual({
      speaker: "",
      text: "We should revisit the hiring plan after the budget review.",
    });
    expect(analysis.full_text).not.toContain("Morning session");
  });

  it("collects checkbox and bullet action items plus speech-detected actions", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(POWER_AUTOMATE, "md");

    expect(analysis.action_items.slice(0, 3)).toEqual([
      "Bob Costa: Validate the dependency list by Friday",
      "Carol Dias: Draft the hiring plan",
      "Alice Silva: Schedule the follow-up meeting",
    ]);
    expect(analysis.action_items).toContain(
      "[Bob Costa] The roadmap looks solid but we must validate dependencies.",
    );
    expect(analysis.action_items).toContain(
      "We should revisit the hiring plan after the budget review.",
    );
  });

  it("extracts open questions from the transcription", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(POWER_AUTOMATE, "md");

    expect(analysis.open_questions).toEqual(["[Carol Dias] What is the hiring timeline for Q3?"]);
  });

  it("records references and skips the change log table", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(POWER_AUTOMATE, "md");

    const references = analysis.segments
      .filter((segment) => segment.speaker === "__REFERENCE__")
      .map((segment) => segment.text);
    expect(references).toEqual(["- Q3 roadmap deck", "- Hiring tracker document"]);
    expect(analysis.full_text).not.toContain("Initial");
  });

  it("derives the title from the H1 when no frontmatter title exists", () => {
    const { parser } = makeParser();
    const md = `# Weekly Sync

**Date:** 2026-07-11
**Participants:** Alice, Bob

> Weekly alignment on the launch checklist.

## 1. Executive Summary

The team reviewed launch readiness and the remaining risks.

## 4. Complete Transcription

Alice: The launch checklist is almost done.
Bob: We must finish the load tests before Friday.

## 5. Action Items

1. Alice: Finish the load test plan
- [ ] Bob: Review the rollback steps
`;
    const analysis = parser.parse(md, "md");

    expect(analysis.title).toBe("Weekly Sync");
    expect(analysis.participants).toEqual(["Alice", "Bob"]);
    expect(analysis.segments).toContainEqual({ speaker: "__META_DATE__", text: "2026-07-11" });
    expect(analysis.segments).toContainEqual({
      speaker: "Alice",
      text: "The launch checklist is almost done.",
    });
    expect(analysis.action_items).toEqual([
      "Alice: Finish the load test plan",
      "Bob: Review the rollback steps",
      "[Bob] We must finish the load tests before Friday.",
    ]);
  });

  it("detects the simple unnumbered section format", () => {
    const { parser } = makeParser();
    const md = `## Executive Summary

- One summary point from the meeting.

## Action Items

- Do the follow-up task
`;
    const analysis = parser.parse(md, "md");

    expect(analysis.segments).toContainEqual({
      speaker: "__SUMMARY__",
      text: "One summary point from the meeting.",
    });
    expect(analysis.action_items).toEqual(["Do the follow-up task"]);
    expect(analysis.title).toBe("General Discussion");
  });

  it("handles Portuguese section names, skips toc/changelog, and keeps unknown sections", () => {
    const { parser } = makeParser();
    const md = `---
title: "Reunião de Planejamento"
---

# Reunião de Planejamento

## Índice

- [Resumo](#resumo)

## Resumo

- Decidimos o escopo da entrega.

## Tópicos

- Escopo da entrega

## Transcrição

**Ana:** Vamos começar pelo escopo.
**Bruno:** Concordo com o escopo proposto.

## Ações

- [ ] Ana: Enviar a ata até sexta

## Referências

Documento de escopo v2

## Estacionamento

**Nota:** Item para a próxima reunião

- Ponto solto sem dono definido

## Changelog

| 1.0 | 2026-07-11 |
`;
    const analysis = parser.parse(md, "md");

    expect(analysis.title).toBe("Reunião de Planejamento");
    expect(analysis.topics.map((topic) => topic.name)).toEqual(["Escopo da entrega"]);
    expect(analysis.participants).toContain("Ana");
    expect(analysis.participants).toContain("Bruno");
    expect(analysis.action_items).toContain("Ana: Enviar a ata até sexta");
    expect(analysis.decisions.join(" ")).toContain("Decidimos o escopo da entrega.");
    expect(analysis.segments).toContainEqual({
      speaker: "__REFERENCE__",
      text: "Documento de escopo v2",
    });
    expect(analysis.segments).toContainEqual({
      speaker: "Nota",
      text: "Item para a próxima reunião",
    });
    expect(analysis.segments).toContainEqual({
      speaker: "",
      text: "Ponto solto sem dono definido",
    });
    expect(analysis.full_text).not.toContain("[Resumo](#resumo)");
    expect(analysis.full_text).not.toContain("2026-07-11");
  });

  it("parses bold participant metadata and semicolon-separated names in the details section", () => {
    const { parser } = makeParser();
    const md = `---
title: "Details Test"
---

## 2. Meeting Details

**Participants:** Alice, Bob; Carol

## 3. Main Topics

- Alpha topic
`;
    const analysis = parser.parse(md, "md");

    expect(analysis.participants).toEqual(["Alice", "Bob", "Carol"]);
  });
});

describe("TranscriptParser — extraction heuristics", () => {
  it("clusters segments into named topics from keyword signals", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(
      [
        "Alice: We need login and oauth for authentication on the platform.",
        "Bob: The database must be postgres with encrypted storage.",
        "Alice: We decided the deployment will use docker containers in the pipeline.",
      ].join("\n"),
      "txt",
    );

    expect(analysis.topics.map((topic) => topic.name)).toEqual([
      "Authentication & Authorization",
      "Data Storage",
      "Deployment & Infrastructure",
    ]);
    expect(analysis.topics[0]).toMatchObject({
      speakers: ["Alice"],
      key_points: [expect.any(String)],
    });
    expect(analysis.title).toBe("Authentication & Authorization");
  });

  it("keeps unmatched leading segments in a General Discussion topic", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(
      [
        "Alice: Welcome everyone and thanks for coming today.",
        "Bob: The api endpoints need webhook support soon.",
      ].join("\n"),
      "txt",
    );

    expect(analysis.topics.map((topic) => topic.name)).toEqual([
      "General Discussion",
      "API Design",
    ]);
  });

  it("extracts deduplicated decisions across all phrasing patterns", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(
      [
        "Alice: We decided to use postgres for storage.",
        "Bob: Something else entirely here for context.",
        "Alice: We decided to use postgres for storage.",
        "Carol: The team approved the new api design.",
        "Dave: The cache layer will be redis for speed.",
      ].join("\n"),
      "txt",
    );

    expect(analysis.decisions).toEqual([
      "[Alice] We decided to use postgres for storage.",
      "[Carol] The team approved the new api design.",
      "[Dave] The cache layer will be redis for speed.",
    ]);
  });

  it("extracts action items from speech signals", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(
      [
        "Alice: Bob needs to update the runbook by Friday.",
        "Bob: I will follow-up on the security review next week.",
        "Carol: This sentence has no action signals at all.",
      ].join("\n"),
      "txt",
    );

    expect(analysis.action_items).toEqual([
      "[Alice] Bob needs to update the runbook by Friday.",
      "[Bob] I will follow-up on the security review next week.",
    ]);
  });

  it("extracts requirements with a minimum text length and dedupes them", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(
      [
        "Alice: The system shall support 500 concurrent users.",
        "Bob: Must go now.",
        "Carol: The platform needs to handle retries for failed jobs.",
        "Alice: The system shall support 500 concurrent users.",
      ].join("\n"),
      "txt",
    );

    expect(analysis.requirements_raw).toEqual([
      "The system shall support 500 concurrent users.",
      "The platform needs to handle retries for failed jobs.",
    ]);
  });

  it("extracts constraints from budget, mandate, and compliance signals", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(
      [
        "Alice: The budget cannot exceed ten thousand dollars this quarter.",
        "Bob: We must use the existing identity provider for login.",
        "Carol: Everything is open for discussion here.",
      ].join("\n"),
      "txt",
    );

    expect(analysis.constraints_mentioned).toEqual([
      "The budget cannot exceed ten thousand dollars this quarter.",
      "We must use the existing identity provider for login.",
    ]);
  });

  it("extracts questions by punctuation and question words", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(
      [
        "Alice: How do we deploy this thing to production",
        "Bob: What is the rollback plan?",
        "Carol: Statements are not questions.",
      ].join("\n"),
      "txt",
    );

    expect(analysis.open_questions).toEqual([
      "[Alice] How do we deploy this thing to production",
      "[Bob] What is the rollback plan?",
    ]);
  });

  it("caps the open questions list at fifteen entries", () => {
    const { parser } = makeParser();
    const lines = Array.from(
      { length: 20 },
      (_, index) => `Alice: Unique question number ${index + 1} for the group?`,
    );
    const analysis = parser.parse(lines.join("\n"), "txt");

    expect(analysis.open_questions).toHaveLength(15);
  });

  it("derives the title from the first segment when no title or topics exist", () => {
    const { parser } = makeParser();
    const analysis = parser.parse('---\nauthor: "Release Bot"\n---\n', "md");

    expect(analysis.title).toBe("Release Bot");
    expect(analysis.participants).toEqual([]);
    expect(analysis.topics).toEqual([]);
  });

  it("skips comments and single-quoted values in YAML frontmatter", () => {
    const { parser } = makeParser();
    const analysis = parser.parse("---\n# Recorder metadata\ntitle: 'Single Quoted'\n---\n", "md");

    expect(analysis.title).toBe("Single Quoted");
  });

  it("estimates duration from word volume for untimed text", () => {
    const { parser } = makeParser();
    const words = Array.from({ length: 300 }, (_, index) => `token${index}`).join(" ");
    const analysis = parser.parse(words, "txt");

    expect(analysis.duration_estimate).toBe("~2 minutes (estimated from text volume)");
  });
});

describe("TranscriptParser — toMarkdown", () => {
  it("renders every populated section with speaker attribution", () => {
    const { parser } = makeParser();
    const analysis = parser.parse(
      [
        "Alice: We decided the api will use webhooks for notifications.",
        "Bob: Alice needs to document the webhook contract by Friday.",
        "Alice: The system shall retry failed webhook deliveries three times.",
        "Bob: The budget cannot cover an external notification vendor.",
        "Alice: What happens when the endpoint is unreachable?",
      ].join("\n"),
      "txt",
    );
    const markdown = parser.toMarkdown(analysis);

    expect(markdown).toContain("# Meeting Transcript: API Design");
    expect(markdown).toContain("**Participants:** Alice, Bob");
    expect(markdown).toContain("## Topics Discussed");
    expect(markdown).toContain("### API Design");
    expect(markdown).toContain("**Key Points:**");
    expect(markdown).toContain("## Decisions");
    expect(markdown).toContain("- [Alice] We decided the api will use webhooks for notifications.");
    expect(markdown).toContain("## Action Items");
    expect(markdown).toContain(
      "- [ ] [Bob] Alice needs to document the webhook contract by Friday.",
    );
    expect(markdown).toContain("## Requirements Identified");
    expect(markdown).toContain("- The system shall retry failed webhook deliveries three times.");
    expect(markdown).toContain("## Constraints Mentioned");
    expect(markdown).toContain("- The budget cannot cover an external notification vendor.");
    expect(markdown).toContain("## Open Questions");
    expect(markdown).toContain("- [Alice] What happens when the endpoint is unreachable?");
    expect(markdown).toContain("## Full Transcript");
    expect(markdown).toContain(
      "**Alice:** We decided the api will use webhooks for notifications.",
    );
  });

  it("omits empty sections and renders unattributed segments plainly", () => {
    const { parser } = makeParser();
    const analysis: TranscriptAnalysis = {
      title: "Sparse",
      participants: [],
      duration_estimate: "~1 minutes",
      segments: [{ speaker: "", text: "Just floating text." }],
      topics: [{ name: "Lonely Topic", summary: "A summary.", speakers: [], key_points: [] }],
      decisions: [],
      action_items: [],
      requirements_raw: [],
      constraints_mentioned: [],
      open_questions: [],
      full_text: "Just floating text.",
    };
    const markdown = parser.toMarkdown(analysis);

    expect(markdown).toContain("# Meeting Transcript: Sparse");
    expect(markdown).toContain("### Lonely Topic");
    expect(markdown).not.toContain("**Key Points:**");
    expect(markdown).not.toContain("## Decisions");
    expect(markdown).not.toContain("## Action Items");
    expect(markdown).not.toContain("## Requirements Identified");
    expect(markdown).not.toContain("## Constraints Mentioned");
    expect(markdown).not.toContain("## Open Questions");
    expect(markdown).toContain("Just floating text.");
    expect(markdown).not.toContain("**:");
  });
});

describe("TranscriptParser — parseFile and format detection", () => {
  it("detects the format from the file extension", async () => {
    const { parser, workspace } = makeParser();
    writeFileSync(join(workspace, "meeting.vtt"), VTT_BASIC);
    writeFileSync(
      join(workspace, "meeting.srt"),
      "1\n00:00:01,000 --> 00:00:04,000\nAlice: Hi there.\n",
    );
    writeFileSync(join(workspace, "notes.md"), "**Alice:** Hello from markdown.");

    const vtt = await parser.parseFile("meeting.vtt");
    const srt = await parser.parseFile("meeting.srt");
    const md = await parser.parseFile("notes.md");

    expect(vtt.segments[0]).toMatchObject({
      speaker: "Alice",
      timestamp: expect.stringContaining("-->"),
    });
    expect(srt.segments[0]).toMatchObject({
      speaker: "Alice",
      timestamp: "00:00:01,000 --> 00:00:04,000",
    });
    expect(md.segments[0]).toEqual({ speaker: "Alice", text: "Hello from markdown." });
  });

  it("detects uppercase extensions case-insensitively", async () => {
    const { parser, workspace } = makeParser();
    writeFileSync(join(workspace, "MEETING.VTT"), VTT_BASIC);

    const analysis = await parser.parseFile("MEETING.VTT");

    expect(analysis.segments[0].timestamp).toBe("00:00:01.000 --> 00:00:04.000");
  });

  it("auto-detects VTT and SRT content inside .txt files", async () => {
    const { parser, workspace } = makeParser();
    writeFileSync(join(workspace, "vtt-content.txt"), VTT_BASIC);
    writeFileSync(
      join(workspace, "srt-content.txt"),
      "1\n00:00:01,000 --> 00:00:04,000\nAlice: Hi there.\n",
    );

    const vtt = await parser.parseFile("vtt-content.txt");
    const srt = await parser.parseFile("srt-content.txt");

    expect(vtt.segments[0].timestamp).toContain("-->");
    expect(srt.segments[0]).toMatchObject({ timestamp: "00:00:01,000 --> 00:00:04,000" });
  });

  it("falls back to plain text for unrecognized content", async () => {
    const { parser, workspace } = makeParser();
    writeFileSync(join(workspace, "plain.txt"), "Alice: plain text line.");

    const analysis = await parser.parseFile("plain.txt");

    expect(analysis.segments).toEqual([{ speaker: "Alice", text: "plain text line." }]);
  });

  it("rejects when the transcript file does not exist", async () => {
    const { parser } = makeParser();

    await expect(parser.parseFile("missing.vtt")).rejects.toThrow();
  });
});
