/**
 * apm/lock.ts — reproducible lockfile for the canonical primitive source.
 *
 * `apm lock` records a sha256 for every file under `.apm/`, plus apm.yml and
 * apm-policy.yml, into apm.lock.yaml. `apm verify-lock` recomputes and diffs,
 * so any drift between the committed primitives/governance files and the
 * lockfile — a hand-edit, a partial upgrade, a corrupted install — is caught
 * deterministically.
 */
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { relative, resolve, sep } from "node:path";
import { parse, stringify } from "yaml";
import { sourcePaths } from "../paths.js";

export const LOCK_SCHEMA_VERSION = 1;

export interface ApmLock {
    schemaVersion: number;
    package: { name: string; version: string };
    primitives: Record<string, string>;
}

function walkFiles(dir: string): string[] {
    if (!existsSync(dir)) return [];
    const out: string[] = [];
    for (const name of readdirSync(dir)) {
        const full = resolve(dir, name);
        if (statSync(full).isDirectory()) out.push(...walkFiles(full));
        else out.push(full);
    }
    return out;
}

function sha256(file: string): string {
    return `sha256:${createHash("sha256").update(readFileSync(file)).digest("hex")}`;
}

/** Compute the sorted `.apm` + governance manifest hash map for a package root. */
export function hashPrimitives(pkgRoot: string): Record<string, string> {
    const { apmDir, apmYml, apmPolicyYml } = sourcePaths(pkgRoot);
    const files = [...walkFiles(apmDir)];
    if (existsSync(apmYml)) files.push(apmYml);
    if (existsSync(apmPolicyYml)) files.push(apmPolicyYml);

    const map: Record<string, string> = {};
    for (const file of files.sort((a, b) => a.localeCompare(b))) {
        map[relative(pkgRoot, file).split(sep).join("/")] = sha256(file);
    }
    return map;
}

export function generateLock(pkgRoot: string): ApmLock {
    const pkg = JSON.parse(
        readFileSync(resolve(pkgRoot, "package.json"), "utf8"),
    ) as { name: string; version: string };
    return {
        schemaVersion: LOCK_SCHEMA_VERSION,
        package: { name: pkg.name, version: pkg.version },
        primitives: hashPrimitives(pkgRoot),
    };
}

export function serializeLock(lock: ApmLock): string {
    return `# Generated by \`specky apm lock\`. Do not edit by hand.\n${stringify(lock)}`;
}

export function lockPath(pkgRoot: string): string {
    return resolve(pkgRoot, "apm.lock.yaml");
}

export interface VerifyResult {
    ok: boolean;
    missing: string[]; // in lock, absent on disk
    changed: string[]; // hash differs
    extra: string[]; // on disk, absent from lock
    error?: string;
}

export function verifyLock(pkgRoot: string): VerifyResult {
    const path = lockPath(pkgRoot);
    if (!existsSync(path)) {
        return {
            ok: false,
            missing: [],
            changed: [],
            extra: [],
            error: "apm.lock.yaml not found — run `specky apm lock`",
        };
    }

    const locked = parse(readFileSync(path, "utf8")) as ApmLock;
    const current = hashPrimitives(pkgRoot);
    const lockedPrimitives = locked.primitives ?? {};

    const missing: string[] = [];
    const changed: string[] = [];
    for (const [file, hash] of Object.entries(lockedPrimitives)) {
        if (!(file in current)) missing.push(file);
        else if (current[file] !== hash) changed.push(file);
    }
    const extra = Object.keys(current).filter((f) => !(f in lockedPrimitives));

    return {
        ok: missing.length === 0 && changed.length === 0 && extra.length === 0,
        missing: missing.sort(),
        changed: changed.sort(),
        extra: extra.sort(),
    };
}
